FROM hckops/kube-base

# https://github.com/weaveworks/eksctl/releases
ARG EKSCTL_VERSION=0.177.0

ENV BIN_ARCH="$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')"

# eksctl
RUN curl -sSL "https://github.com/weaveworks/eksctl/releases/download/v${EKSCTL_VERSION}/eksctl_$(uname -s)_${BIN_ARCH}.tar.gz" | tar -xzf - -C /usr/local/bin && \
  chmod +x /usr/local/bin/eksctl && \
  eksctl version
